// <auto-generated />
using System;
using Albenny_P2_AP1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Albenny_P2_AP1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201103011025_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Albenny_P2_AP1.Entidades.Proyectos", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("TiempoTotal")
                        .HasColumnType("REAL");

                    b.HasKey("ProyectoId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Albenny_P2_AP1.Entidades.ProyectosDetalle", b =>
                {
                    b.Property<int>("ProyectosDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<double>("Tiempo")
                        .HasColumnType("REAL");

                    b.Property<int>("TipoTareasId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProyectosDetalleId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("TipoTareasId");

                    b.ToTable("ProyectosDetalle");
                });

            modelBuilder.Entity("Albenny_P2_AP1.Entidades.TiposTareas", b =>
                {
                    b.Property<int>("TipoTareasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("TipoTareasId");

                    b.ToTable("TiposTareas");

                    b.HasData(
                        new
                        {
                            TipoTareasId = 1,
                            TipoTarea = "Analisis"
                        },
                        new
                        {
                            TipoTareasId = 2,
                            TipoTarea = "Diseño"
                        },
                        new
                        {
                            TipoTareasId = 3,
                            TipoTarea = "Programación"
                        },
                        new
                        {
                            TipoTareasId = 4,
                            TipoTarea = "Prueba"
                        });
                });

            modelBuilder.Entity("Albenny_P2_AP1.Entidades.ProyectosDetalle", b =>
                {
                    b.HasOne("Albenny_P2_AP1.Entidades.Proyectos", null)
                        .WithMany("Detalle")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Albenny_P2_AP1.Entidades.TiposTareas", "tiposTareas")
                        .WithMany()
                        .HasForeignKey("TipoTareasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
